" dein.vim
source ~/.dotfiles/.vim/.vimrc.dein
" 画面表示
source ~/.dotfiles/.vim/.vimrc.screen
" プログラム
source ~/.dotfiles/.vim/.vimrc.program
" カーソル移動
source ~/.dotfiles/.vim/.vimrc.cursor
" インデント
source ~/.dotfiles/.vim/.vimrc.indent
" タブ
source ~/.dotfiles/.vim/.vimrc.tab
" ファイル処理
source ~/.dotfiles/.vim/.vimrc.file
" 検索/置換
source ~/.dotfiles/.vim/.vimrc.search
" 動作環境との統合
source ~/.dotfiles/.vim/.vimrc.environment
" コマンドライン
source ~/.dotfiles/.vim/.vimrc.cli
